### PR TITLE
Add latest version and version info to each version

### PR DESCRIPTION
**Pull request by cklein**
For some copy&paste happiness.

### CODE REVIEW

**Comment by asottile** [comment]
Thanks for the PR!

**Comment by asottile** [comment]
@cklein you can see some example output here: https://chriskuehl.github.io/dumb-pypi/test-repo/simple/testify/

**Comment by chriskuehl** [comment]
Looks great, thanks @cklein!

**Comment by chriskuehl** [comment]
Released as v1.1.0.

**Pull request merged**
